# Generated by Django 6.0.4 on 2026-04-19 10:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color_theme',
            field=models.CharField(default='success', help_text='Bootstrap color (success, info, warning, primary)', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='bi-tag', help_text='Bootstrap icon class (e.g., bi-laptop)', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='min_stock_level',
            field=models.IntegerField(default=5),
        ),
    ]
